"""
rag.py
======
Embedding creation, storage, retrieval, and answer generation.

Storage backend: Cloudinary (raw for embeddings/PDFs, image for page PNGs).
Local disk is used only as a short-lived temp buffer during a single request.
All persistent I/O goes through cloudinary_storage.

Key fix (2025-06):
    PDFs generated by many resume builders / LaTeX tools embed text without
    proper inter-word spacing.  pdfplumber then extracts entire phrases as a
    single "word" token like "eInfochips(AnArrowCompany),SoftwareEngineerIntern".
    We address this at two levels:

    1. pdf_utils.extract_pages_with_positions now uses x_tolerance=1 so that
       only characters physically touching are merged into one token — this
       separates most fused words at extraction time.

    2. _find_match_in_words has a third matching strategy: "fused-blob scan".
       For each target token we check whether it appears as a substring of any
       page token.  When the target sequence can be covered by consecutive
       page blobs this way, we return those blobs as the matched words.  This
       handles the residual cases where x_tolerance=1 is still not enough to
       split a tightly-kerned run of characters.
"""

import io
import os
import pickle
import re
import json
import string

import numpy as np
from dotenv import load_dotenv
from openai import OpenAI

from cloudinary_storage import (
    download_embeddings,
    download_pdf,
    upload_embeddings,
    upload_image,
)
from pdf_utils import get_pdf_image_from_bytes

load_dotenv()

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"),
)

EMBEDDING_MODEL = "text-embedding-3-small"

_JOINERS = re.compile(r'[-–—/]')

# Fuzzy matching is only attempted for highlights at least this many tokens
# long.  Short highlights (e.g. a 2-token name) have too high a false-positive
# rate at any reasonable threshold.
_MIN_TOKENS_FOR_FUZZY = 6

# Fraction of tokens that must agree for a fuzzy window to be accepted.
_FUZZY_THRESHOLD = 0.85


# ── token normalisation ───────────────────────────────────────────────────────

def normalize_tokens(text: str) -> list[str]:
    """
    Convert a text string into a list of comparable tokens.

    1. Replace joiners (-, –, —, /) with spaces.
    2. Replace newlines with spaces.
    3. Split on whitespace.
    4. Lowercase and strip punctuation from every token.
    5. Drop empty strings.
    """
    text = _JOINERS.sub(' ', text)
    text = text.replace('\n', ' ')
    tokens = []
    for word in text.split():
        cleaned = word.lower().strip().translate(
            str.maketrans('', '', string.punctuation)
        )
        if cleaned:
            tokens.append(cleaned)
    return tokens


def parse_llm_response(raw: str) -> dict:
    try:
        match = re.search(r'\{[\s\S]*\}', raw)
        if match:
            return json.loads(match.group())
    except Exception:
        pass
    return {"answer": raw, "highlights": []}


# ── embeddings persistence ────────────────────────────────────────────────────

def save_embeddings(user_id: str, file_id: str, data: dict) -> None:
    payload = {
        "user_id":    user_id,
        "file_id":    file_id,
        "chunks":     data["chunks"],
        "embeddings": data["embeddings"],
    }
    upload_embeddings(user_id, file_id, pickle.dumps(payload))


def load_embeddings(user_id: str, file_id: str) -> dict | None:
    data_bytes = download_embeddings(user_id, file_id)
    if data_bytes is None:
        return None
    data = pickle.loads(data_bytes)
    if data.get("user_id") != user_id or data.get("file_id") != file_id:
        return None
    return data


# ── embedding creation ────────────────────────────────────────────────────────

def create_embeddings(chunks: list[dict]) -> list[dict]:
    texts    = [c["text"] for c in chunks]
    response = client.embeddings.create(model=EMBEDDING_MODEL, input=texts)
    return [
        {
            "chunk_id":    i,
            "text":        chunks[i]["text"],
            "page_number": chunks[i]["page_number"],
            "words":       chunks[i].get("words"),
            "embedding":   response.data[i].embedding,
        }
        for i in range(len(chunks))
    ]


# ── retrieval ─────────────────────────────────────────────────────────────────

def cosine_similarity(a, b) -> float:
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))


def retrieve_top_chunks(
    query_embedding: list[float],
    chunk_embeddings: list[dict],
    top_k: int = 5,
) -> list[tuple]:
    """Returns list of (score, text, page_number, words)."""
    scored = [
        (
            cosine_similarity(query_embedding, item["embedding"]),
            item["text"],
            item["page_number"],
            item.get("words"),
        )
        for item in chunk_embeddings
    ]
    scored.sort(reverse=True, key=lambda x: x[0])
    return scored[:top_k]


# ── generation ────────────────────────────────────────────────────────────────

def generate_answer(query: str, context: str, history: list | None = None) -> str:
    system_prompt = """
You are a helpful assistant answering questions from a document.

Return ONLY valid JSON in this exact format:
{
  "answer": "...",
  "highlights": [
    {
      "text": "EXACT substring copied character-for-character from context",
      "page": <number>,
      "type": "direct" | "evidence"
    }
  ]
}

RULES:
- "direct"   = sentence/passage that directly answers the question.
- "evidence" = supporting context when no direct answer exists.
- Copy highlight text EXACTLY from context — no rephrasing, no added words.
- Keep each highlight SHORT: one sentence or clause, MAXIMUM 15 words.
  Do NOT paste multi-sentence blocks as one highlight entry.
  Use multiple highlight objects (one per sentence) instead.
- You may include multiple highlights from different pages.
- ALWAYS include at least one highlight.
"""
    messages = [{"role": "system", "content": system_prompt}]
    if history:
        for turn in history[-4:]:
            messages.append({"role": turn["role"], "content": turn["content"]})
    messages.append({
        "role":    "user",
        "content": f"Context:\n{context}\n\nQuestion: {query}",
    })
    response = client.chat.completions.create(
        model="openai/gpt-4o-mini",
        messages=messages,
    )
    return response.choices[0].message.content


# ── main RAG pipeline ─────────────────────────────────────────────────────────

def answer_from_chunks(
    query: str,
    chunk_embeddings: list[dict],
    user_id: str,
    file_id: str,
    history: list | None = None,
) -> tuple[str, list, list]:
    """
    Returns (answer, highlights, images).
    """
    query_emb  = client.embeddings.create(model=EMBEDDING_MODEL, input=query).data[0].embedding
    top_chunks = retrieve_top_chunks(query_emb, chunk_embeddings, top_k=5)

    context = "\n\n".join(
        f"[Page {page}]\n{chunk}" for _, chunk, page, _ in top_chunks
    )

    raw    = generate_answer(query, context, history=history)
    parsed = parse_llm_response(raw)

    answer     = parsed["answer"]
    highlights = parsed.get("highlights", [])

    if not highlights:
        _, top_text, top_page, _ = top_chunks[0]
        first_sentence = top_text.split(".")[0].strip()
        highlights = [{
            "text": first_sentence or top_text[:120],
            "page": top_page,
            "type": "evidence",
        }]

    pdf_bytes = download_pdf(user_id, file_id)

    # Build one flat, reading-order-sorted word list per page from ALL chunks.
    # Deduplication is by object identity because overlapping chunks share
    # the same word dict objects.
    all_words_by_page: dict[int, list[dict]] = {}
    for item in chunk_embeddings:
        words = item.get("words")
        page  = item.get("page_number")
        if not words or page is None:
            continue
        if page not in all_words_by_page:
            all_words_by_page[page] = []
        existing_ids = {id(w) for w in all_words_by_page[page]}
        for w in words:
            if id(w) not in existing_ids:
                all_words_by_page[page].append(w)
                existing_ids.add(id(w))

    for page_words in all_words_by_page.values():
        page_words.sort(key=lambda w: (round(w["top"]), w["x0"]))

    images = highlight_sources(
        user_id, file_id, top_chunks, highlights, pdf_bytes, all_words_by_page
    )

    if not images and pdf_bytes:
        images = _render_page_plain(user_id, file_id, pdf_bytes, top_chunks[0][2])

    return answer, highlights, images


# ── plain page render (no boxes) ─────────────────────────────────────────────

def _render_page_plain(
    user_id: str,
    file_id: str,
    pdf_bytes: bytes,
    page_number: int,
) -> list[dict]:
    try:
        img = get_pdf_image_from_bytes(pdf_bytes, page_number)
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        secure_url = upload_image(user_id, file_id, page_number, buf.getvalue())
        return [{"page": page_number, "types": ["evidence"], "image_url": secure_url}]
    except Exception:
        return []


# ── highlight matching ────────────────────────────────────────────────────────

def _tokens_covered_by_blob(target_tokens: list[str], blob_token: str) -> int:
    """
    How many tokens from the START of target_tokens are contained inside
    blob_token (a fused pdfplumber word with no spaces)?

    E.g. blob="einfochipsanarrowcompanysoftwareengineerintern"
         target=["einfochips","an","arrow","company","software","engineer","intern"]
         → returns 7  (all seven fit inside the blob in order)

    We do a greedy left-to-right scan: for each target token check whether it
    appears next in the remaining blob suffix.  This is O(n * len(blob)) but
    blobs are short so it's fine.
    """
    pos = 0
    count = 0
    for tok in target_tokens:
        idx = blob_token.find(tok, pos)
        if idx == -1:
            break
        pos = idx + len(tok)
        count += 1
    return count


def _find_match_in_words(
    target_tokens: list[str],
    words: list[dict],
) -> list[dict] | None:
    """
    Locate target_tokens as a contiguous span in the page word list.

    Three strategies, tried in order:

    1. Exact — normalised expanded token stream contains target verbatim.
       Works when x_tolerance=1 successfully separated all words.

    2. Fused-blob — the PDF did not have proper inter-word spacing so
       pdfplumber produced multi-word blobs even with tight tolerances.
       We greedily consume target tokens by checking whether each blob
       contains the next N target tokens as an embedded substring.
       This is the key fix for resumes produced by LaTeX / tight-kerning
       generators.

    3. Fuzzy — best sliding window with score ≥ _FUZZY_THRESHOLD.
       Only attempted for highlights ≥ _MIN_TOKENS_FOR_FUZZY tokens to
       avoid false positives on short strings.
    """
    if not target_tokens or not words:
        return None

    # Build expanded token / word lists (same as before)
    expanded_tokens: list[str]  = []
    expanded_words:  list[dict] = []

    for word in words:
        sub_tokens = normalize_tokens(word["text"])
        if not sub_tokens:
            continue
        expanded_tokens.extend(sub_tokens)
        expanded_words.extend([word] * len(sub_tokens))

    n = len(target_tokens)

    def _collect(start: int, length: int) -> list[dict]:
        result: list[dict] = []
        seen: set[int] = set()
        for w in expanded_words[start: start + length]:
            wid = id(w)
            if wid not in seen:
                result.append(w)
                seen.add(wid)
        return result

    # ── Strategy 1: exact ────────────────────────────────────────────────────
    if n <= len(expanded_tokens):
        for i in range(len(expanded_tokens) - n + 1):
            if expanded_tokens[i: i + n] == target_tokens:
                return _collect(i, n)

    # ── Strategy 2: fused-blob scan ──────────────────────────────────────────
    #
    # Walk target_tokens left-to-right.  For each page word (blob) in reading
    # order try to consume as many target tokens as possible by checking
    # whether they appear embedded in the blob's normalised text.
    #
    # Example:
    #   blob normalised = "einfochipsanarrowcompanysoftwareengineerintern"
    #   target tokens   = ["einfochips","an","arrow","company","software","engineer","intern"]
    #   → all 7 consumed by this one blob
    #
    # We accept the match when ALL target tokens have been consumed.

    matched_words_blob: list[dict] = []
    remaining = list(target_tokens)  # tokens still to consume
    consuming = False                # have we started matching?

    for word in words:
        blob = normalize_tokens(word["text"])
        if not blob:
            continue
        blob_str = "".join(blob)  # fused normalised form of this page word

        if not consuming:
            # Try to start consuming from this blob
            consumed = _tokens_covered_by_blob(remaining, blob_str)
            if consumed > 0:
                consuming = True
                matched_words_blob.append(word)
                remaining = remaining[consumed:]
                if not remaining:
                    break
        else:
            # Continue consuming; we expect the next target tokens to be in
            # this blob or in subsequent blobs.
            consumed = _tokens_covered_by_blob(remaining, blob_str)
            if consumed > 0:
                matched_words_blob.append(word)
                remaining = remaining[consumed:]
                if not remaining:
                    break
            else:
                # Gap — blob doesn't contain next expected token.
                # Allow skipping icon/cid blobs that aren't real text.
                blob_raw = word["text"]
                if blob_raw.startswith("(cid:") or len(blob_str) <= 2:
                    continue  # skip non-text artefacts
                # Otherwise reset — we lost the sequence
                matched_words_blob = []
                remaining = list(target_tokens)
                consuming = False

    if not remaining and matched_words_blob:
        return matched_words_blob

    # ── Strategy 3: fuzzy ────────────────────────────────────────────────────
    if n < _MIN_TOKENS_FOR_FUZZY or n > len(expanded_tokens):
        return None

    best_score = 0.0
    best_start = -1

    for i in range(len(expanded_tokens) - n + 1):
        window  = expanded_tokens[i: i + n]
        matches = sum(a == b for a, b in zip(target_tokens, window))
        score   = matches / n
        if score > best_score:
            best_score = score
            best_start = i

    if best_score >= _FUZZY_THRESHOLD and best_start >= 0:
        return _collect(best_start, n)

    return None


# ── highlighting ──────────────────────────────────────────────────────────────

def highlight_sources(
    user_id: str,
    file_id: str,
    top_chunks: list[tuple],
    highlights: list[dict],
    pdf_bytes: bytes | None,
    all_words_by_page: dict[int, list[dict]] | None = None,
) -> list[dict]:
    """
    Draw highlight boxes on PDF pages and upload annotated PNGs to Cloudinary.

    Coordinate note
    ---------------
    pdfplumber's PageImage.draw_rect() accepts coordinates in PDF point space
    (the same space as extract_words output).  It handles DPI scaling
    internally.  Do NOT multiply coordinates by any scale factor.
    """
    if not highlights or pdf_bytes is None:
        return []

    legacy_chunks_by_page: dict[int, list[list[dict]]] | None = None
    if all_words_by_page is None:
        legacy_chunks_by_page = {}
        for _, _, page, words in top_chunks:
            if words:
                legacy_chunks_by_page.setdefault(page, []).append(words)

    # Render every highlighted page upfront — one PageImage per page that
    # accumulates all draw_rect calls for that page.
    page_images: dict[int, object]       = {}
    page_highlight_types: dict[int, set] = {}

    for h in highlights:
        p = h.get("page")
        if p is not None and p not in page_images:
            try:
                page_images[p] = get_pdf_image_from_bytes(pdf_bytes, p)
            except Exception:
                pass

    for highlight in highlights:
        raw_text    = highlight.get("text", "").strip()
        target_page = highlight.get("page")
        h_type      = highlight.get("type", "evidence")

        if not raw_text or target_page is None:
            continue
        if target_page not in page_images:
            continue

        target_tokens = normalize_tokens(raw_text)
        if not target_tokens:
            continue

        page_highlight_types.setdefault(target_page, set()).add(h_type)

        matched = None
        if all_words_by_page is not None:
            page_words = all_words_by_page.get(target_page, [])
            if page_words:
                matched = _find_match_in_words(target_tokens, page_words)
        else:
            for words in (legacy_chunks_by_page or {}).get(target_page, []):
                matched = _find_match_in_words(target_tokens, words)
                if matched:
                    break

        if matched:
            x0     = min(w["x0"]     for w in matched)
            x1     = max(w["x1"]     for w in matched)
            top    = min(w["top"]    for w in matched)
            bottom = max(w["bottom"] for w in matched)

            color = "green" if h_type == "direct" else "orange"
            page_images[target_page].draw_rect(
                (x0, top, x1, bottom),
                stroke=color,
                stroke_width=2,
            )

    images = []
    for page, img in page_images.items():
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        secure_url = upload_image(user_id, file_id, page, buf.getvalue())
        images.append({
            "page":      page,
            "types":     list(page_highlight_types.get(page, {"evidence"})),
            "image_url": secure_url,
        })

    images.sort(key=lambda x: x["page"])
    return images


def generate_session_title(query: str) -> str:
    """
    Ask the LLM to produce a short (≤6 word) chat title from the first user question.
    Falls back to a truncated query if the call fails.
    """
    print(f"Generating session title from query: {query}")
    try:
        response = client.chat.completions.create(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "Generate a concise chat title (maximum 6 words, no quotes, "
                        "no punctuation at the end) that captures what the user is asking. "
                        "Reply with ONLY the title — nothing else."
                    ),
                },
                {"role": "user", "content": query},
            ],
            max_tokens=20,
        )
        print(f"LLM response for title generation: {response.choices[0].message.content}")
        title = response.choices[0].message.content.strip().strip('"').strip("'")
        return title or query[:60]
    except Exception:
        return query[:60]